// Published versions are immutable: change the version when any wording changes.
export const NFT_LEGAL_VERSION = '2026-09-13.1'
export const NFT_CONSENT_TEXT = 'I voluntarily consent to TUM Blockchain Club publishing my NFT artwork (including my portrait), display name, department, batch/club period, Member Flex and membership status, and updating these membership fields during the NFT lifecycle. My display name, wallet/asset addresses, metadata link and transactions will be public on Solana; artwork and metadata will be publicly hosted and accessible worldwide. Solana history cannot be erased, even after burning the NFT, and third parties may keep copies. I can withdraw consent for future publication by contacting info@tum-blockchain.com. Requesting an NFT is optional and declining does not affect my club membership. I accept the Membership NFT Terms and acknowledge the Privacy Policy.'

export const NFT_TERMS = [
  { title: '1. Optional membership collectible', text: 'The Solana membership NFT is an optional digital club collectible. It is not an investment, transferable club membership or proof of identity. Declining or withdrawing publication consent does not affect club membership.' },
  { title: '2. Your submission and publication permission', text: 'Use a nickname or first name with a surname initial, not a full legal name. Submit only portraits and statements you have the right to publish. Your separate, affirmative publication consent covers the artwork, display name, department, batch/club period, Member Flex and membership status, including updates to these membership fields. Do not submit sensitive information about yourself or others.' },
  { title: '3. Public and permanent data', text: 'The NFT name contains your display name directly on Solana. Asset and wallet addresses, the metadata link and transaction history are also public. Rendered artwork and metadata are publicly hosted, not stored as image bytes on Solana. Blockchain history cannot be erased by updating or burning an NFT. Wallets, explorers and other third parties may retain worldwide copies after hosted files are removed. A nickname or club wallet does not guarantee anonymity.' },
  { title: '4. Wallet choice and club authority', text: 'At request time you choose initial custody in the club wallet or direct minting to your own Solana wallet. Later claims and wallet recovery require a member request and authorized NFT administrator approval. The club retains permanent update, freeze, transfer and burn authority, including after a transfer to your wallet. It may update membership fields, mark alumni status or burn the NFT when membership ends or publication consent is withdrawn.' },
  { title: '5. Wallet responsibility and availability', text: 'Check your wallet address carefully and secure your own wallet. The service depends on Solana, RPC, storage and wallet providers; availability and third-party display cannot be guaranteed. These terms do not exclude mandatory statutory rights or liabilities.' },
  { title: '6. Withdrawal and contact', text: 'For withdrawal, deletion or questions, contact info@tum-blockchain.com. Withdrawal stops future consent-based publication and initiates removal of club-hosted personal NFT files and revocation; it cannot erase blockchain history or independent copies. Read the Membership NFT Privacy Policy at /privacy for details.' },
]
export const NFT_PRIVACY = [
  { title: '1. Controller and contact', text: 'TUM Blockchain Club e.V., Arcisstraße 21, 80333 Munich, Germany is responsible for the platform’s NFT processing. Contact info@tum-blockchain.com for privacy requests.' },
  { title: '2. Data and purposes', text: 'We process member records, source portraits, display names, department, batch/club period, Member Flex, membership status, wallet/asset addresses, requests, reviews and transactions to issue and administer optional membership NFTs. We record who consented, when, for which request and which versions of the publication statement, terms and privacy notice were shown. The original source upload and consent records are kept in private platform storage.' },
  { title: '3. Legal bases and choice', text: 'Publication of your portrait and profile fields, including lifecycle updates, is based on your voluntary consent under Article 6(1)(a) GDPR. Request administration is necessary to provide the service you request under Article 6(1)(b). Security and limited evidence retention serve our legitimate interests in preventing misuse and establishing or defending legal claims under Article 6(1)(f); consent evidence also supports our accountability obligations under Articles 5(2) and 7(1). An NFT is optional. Refusal or withdrawal does not affect club membership. We do not use this flow for automated decisions with legal or similarly significant effects.' },
  { title: '4. Exactly what becomes public', text: 'On Solana: your display name in the NFT name, wallet and asset addresses, metadata link and transaction history. In public hosted artwork/metadata: your portrait as part of the NFT artwork, display name, department, batch/club period, Member Flex and membership status. Technical file and asset identifiers may also be visible in URLs. Emails and full legal names are not intentionally included in generated metadata. A nickname is not a guarantee of anonymity. Authorized platform operators can access private source uploads; the approved rendered portrait becomes public.' },
  { title: '5. Recipients and worldwide access', text: 'The platform uses Supabase for database and storage and Vercel for application hosting; Solana RPC services relay chain operations. Public data can be retrieved worldwide by independent validators, wallets, explorers and any other recipient. The club cannot control their copying or subsequent processing. This notice does not itself establish a GDPR Chapter V transfer mechanism for infrastructure providers; applicable provider processing agreements, hosting regions and transfer safeguards must be assessed separately. You may request details from the contact above.' },
  { title: '6. Retention and withdrawal', text: 'Unminted requests can be deleted in the portal. You can withdraw consent at any time by contacting info@tum-blockchain.com, without affecting the lawfulness of processing before withdrawal. Withdrawal initiates revocation and removal of club-hosted personal artwork, metadata and source files. Blockchain history and independent cached copies cannot be erased by the club, including after burn. Minimal consent and operational evidence may be retained separately as necessary for accountability and legal claims, with retention determined by applicable limitation periods and outstanding disputes; it is not published. Keeping evidence does not authorize further NFT publication.' },
  { title: '7. Your rights', text: 'You may request access, correction, erasure, restriction and portability where applicable, withdraw consent, and object to processing based on legitimate interests. You may complain to a supervisory authority, including the Bavarian State Office for Data Protection Supervision (BayLDA). Blockchain permanence is a technical limitation, not a waiver of your statutory rights. Contact info@tum-blockchain.com to exercise your rights. The related Membership NFT Terms are available at /terms.' },
]
export const NFT_LEGAL_DOCUMENTS = { version: NFT_LEGAL_VERSION, consent: NFT_CONSENT_TEXT, terms: NFT_TERMS, privacy: NFT_PRIVACY }
export function acceptsCurrentNftLegal(payload: { publication_consent?: unknown; legal_version?: unknown }) {
  return payload.publication_consent === true && payload.legal_version === NFT_LEGAL_VERSION
}
