export const universities = [
  { name: 'TUM', fullName: 'Technical University of Munich', country: 'DE', city: 'Munich' },
  { name: 'LMU', fullName: 'Ludwig Maximilian University of Munich', country: 'DE', city: 'Munich' },
  { name: 'HM', fullName: 'Munich University of Applied Sciences', country: 'DE', city: 'Munich' },
  { name: 'UniBw München', fullName: 'Universität der Bundeswehr München', country: 'DE', city: 'Munich' },
  { name: 'Munich Business School', fullName: 'Munich Business School', country: 'DE', city: 'Munich' },
  { name: 'Hochschule Fresenius München', fullName: 'Hochschule Fresenius München', country: 'DE', city: 'Munich' },
  { name: 'IU München', fullName: 'IU International University Munich', country: 'DE', city: 'Munich' },
  { name: 'Macromedia München', fullName: 'Macromedia University Munich', country: 'DE', city: 'Munich' },
  { name: 'HMTM', fullName: 'Hochschule für Musik und Theater München', country: 'DE', city: 'Munich' },
  { name: 'AMD München', fullName: 'Akademie Mode & Design München', country: 'DE', city: 'Munich' },
  
  { name: 'Uni Augsburg', fullName: 'University of Augsburg', country: 'DE', city: 'Augsburg' },
  { name: 'HS Augsburg', fullName: 'Hochschule Augsburg', country: 'DE', city: 'Augsburg' },
  { name: 'Uni Passau', fullName: 'University of Passau', country: 'DE', city: 'Passau' },
  { name: 'TH Ingolstadt', fullName: 'Technische Hochschule Ingolstadt', country: 'DE', city: 'Ingolstadt' },
  { name: 'KU Eichstätt', fullName: 'Catholic University of Eichstätt-Ingolstadt', country: 'DE', city: 'Eichstätt' },
  { name: 'Uni Regensburg', fullName: 'University of Regensburg', country: 'DE', city: 'Regensburg' },
  { name: 'OTH Regensburg', fullName: 'Ostbayerische Technische Hochschule Regensburg', country: 'DE', city: 'Regensburg' },
  { name: 'Uni Bayreuth', fullName: 'University of Bayreuth', country: 'DE', city: 'Bayreuth' },
  { name: 'Uni Würzburg', fullName: 'University of Würzburg', country: 'DE', city: 'Würzburg' },
  { name: 'FHWS', fullName: 'Hochschule Würzburg-Schweinfurt', country: 'DE', city: 'Würzburg' },
  { name: 'Uni Erlangen-Nürnberg', fullName: 'Friedrich-Alexander-Universität Erlangen-Nürnberg', country: 'DE', city: 'Erlangen' },
  { name: 'FAU', fullName: 'Friedrich-Alexander-Universität Erlangen-Nürnberg', country: 'DE', city: 'Erlangen' },
  { name: 'TH Nürnberg', fullName: 'Technische Hochschule Nürnberg', country: 'DE', city: 'Nuremberg' },
  { name: 'HS Landshut', fullName: 'Hochschule Landshut', country: 'DE', city: 'Landshut' },
  { name: 'HS Rosenheim', fullName: 'Hochschule Rosenheim', country: 'DE', city: 'Rosenheim' },
  { name: 'HS Weihenstephan', fullName: 'Hochschule Weihenstephan-Triesdorf', country: 'DE', city: 'Freising' },
  { name: 'HS Kempten', fullName: 'Hochschule Kempten', country: 'DE', city: 'Kempten' },
  { name: 'HS Neu-Ulm', fullName: 'Hochschule Neu-Ulm', country: 'DE', city: 'Neu-Ulm' },
  
  { name: 'Uni Heidelberg', fullName: 'Heidelberg University', country: 'DE', city: 'Heidelberg' },
  { name: 'KIT', fullName: 'Karlsruhe Institute of Technology', country: 'DE', city: 'Karlsruhe' },
  { name: 'Uni Karlsruhe', fullName: 'University of Karlsruhe', country: 'DE', city: 'Karlsruhe' },
  { name: 'HS Karlsruhe', fullName: 'Hochschule Karlsruhe', country: 'DE', city: 'Karlsruhe' },
  { name: 'Uni Mannheim', fullName: 'University of Mannheim', country: 'DE', city: 'Mannheim' },
  { name: 'HS Mannheim', fullName: 'Hochschule Mannheim', country: 'DE', city: 'Mannheim' },
  { name: 'Uni Freiburg', fullName: 'University of Freiburg', country: 'DE', city: 'Freiburg' },
  { name: 'Uni Stuttgart', fullName: 'University of Stuttgart', country: 'DE', city: 'Stuttgart' },
  { name: 'HS Stuttgart', fullName: 'Hochschule für Technik Stuttgart', country: 'DE', city: 'Stuttgart' },
  { name: 'Uni Hohenheim', fullName: 'University of Hohenheim', country: 'DE', city: 'Stuttgart' },
  { name: 'Uni Tübingen', fullName: 'University of Tübingen', country: 'DE', city: 'Tübingen' },
  { name: 'Uni Ulm', fullName: 'Ulm University', country: 'DE', city: 'Ulm' },
  { name: 'Uni Konstanz', fullName: 'University of Konstanz', country: 'DE', city: 'Konstanz' },
  { name: 'HTWG Konstanz', fullName: 'Hochschule Konstanz', country: 'DE', city: 'Konstanz' },
  { name: 'HS Pforzheim', fullName: 'Hochschule Pforzheim', country: 'DE', city: 'Pforzheim' },
  { name: 'HS Reutlingen', fullName: 'Hochschule Reutlingen', country: 'DE', city: 'Reutlingen' },
  { name: 'DHBW', fullName: 'Duale Hochschule Baden-Württemberg', country: 'DE', city: 'Stuttgart' },
  
  { name: 'HU Berlin', fullName: 'Humboldt University of Berlin', country: 'DE', city: 'Berlin' },
  { name: 'FU Berlin', fullName: 'Free University of Berlin', country: 'DE', city: 'Berlin' },
  { name: 'TU Berlin', fullName: 'Technical University of Berlin', country: 'DE', city: 'Berlin' },
  { name: 'Charité', fullName: 'Charité - Universitätsmedizin Berlin', country: 'DE', city: 'Berlin' },
  { name: 'HTW Berlin', fullName: 'Hochschule für Technik und Wirtschaft Berlin', country: 'DE', city: 'Berlin' },
  { name: 'Beuth HS', fullName: 'Beuth Hochschule für Technik Berlin', country: 'DE', city: 'Berlin' },
  { name: 'Uni Potsdam', fullName: 'University of Potsdam', country: 'DE', city: 'Potsdam' },
  { name: 'HPI', fullName: 'Hasso Plattner Institute', country: 'DE', city: 'Potsdam' },
  
  { name: 'RWTH Aachen', fullName: 'RWTH Aachen University', country: 'DE', city: 'Aachen' },
  { name: 'FH Aachen', fullName: 'FH Aachen University of Applied Sciences', country: 'DE', city: 'Aachen' },
  { name: 'Uni Köln', fullName: 'University of Cologne', country: 'DE', city: 'Cologne' },
  { name: 'TH Köln', fullName: 'TH Köln - University of Applied Sciences', country: 'DE', city: 'Cologne' },
  { name: 'Uni Bonn', fullName: 'University of Bonn', country: 'DE', city: 'Bonn' },
  { name: 'HS Bonn-Rhein-Sieg', fullName: 'Hochschule Bonn-Rhein-Sieg', country: 'DE', city: 'Sankt Augustin' },
  { name: 'Uni Düsseldorf', fullName: 'Heinrich Heine University Düsseldorf', country: 'DE', city: 'Düsseldorf' },
  { name: 'HS Düsseldorf', fullName: 'Hochschule Düsseldorf', country: 'DE', city: 'Düsseldorf' },
  { name: 'Uni Duisburg-Essen', fullName: 'University of Duisburg-Essen', country: 'DE', city: 'Essen' },
  { name: 'TU Dortmund', fullName: 'TU Dortmund University', country: 'DE', city: 'Dortmund' },
  { name: 'FH Dortmund', fullName: 'FH Dortmund University of Applied Sciences', country: 'DE', city: 'Dortmund' },
  { name: 'Uni Bochum', fullName: 'Ruhr University Bochum', country: 'DE', city: 'Bochum' },
  { name: 'HS Bochum', fullName: 'Hochschule Bochum', country: 'DE', city: 'Bochum' },
  { name: 'Uni Münster', fullName: 'University of Münster', country: 'DE', city: 'Münster' },
  { name: 'WWU', fullName: 'Westfälische Wilhelms-Universität Münster', country: 'DE', city: 'Münster' },
  { name: 'FH Münster', fullName: 'FH Münster University of Applied Sciences', country: 'DE', city: 'Münster' },
  { name: 'Uni Bielefeld', fullName: 'Bielefeld University', country: 'DE', city: 'Bielefeld' },
  { name: 'Uni Paderborn', fullName: 'Paderborn University', country: 'DE', city: 'Paderborn' },
  { name: 'Uni Siegen', fullName: 'University of Siegen', country: 'DE', city: 'Siegen' },
  { name: 'Uni Wuppertal', fullName: 'University of Wuppertal', country: 'DE', city: 'Wuppertal' },
  
  { name: 'Uni Frankfurt', fullName: 'Goethe University Frankfurt', country: 'DE', city: 'Frankfurt' },
  { name: 'Frankfurt School', fullName: 'Frankfurt School of Finance & Management', country: 'DE', city: 'Frankfurt' },
  { name: 'Uni Mainz', fullName: 'Johannes Gutenberg University Mainz', country: 'DE', city: 'Mainz' },
  { name: 'TU Darmstadt', fullName: 'Technische Universität Darmstadt', country: 'DE', city: 'Darmstadt' },
  { name: 'HS Darmstadt', fullName: 'Hochschule Darmstadt', country: 'DE', city: 'Darmstadt' },
  { name: 'Uni Gießen', fullName: 'Justus Liebig University Gießen', country: 'DE', city: 'Gießen' },
  { name: 'Uni Marburg', fullName: 'Philipps-Universität Marburg', country: 'DE', city: 'Marburg' },
  { name: 'Uni Kassel', fullName: 'University of Kassel', country: 'DE', city: 'Kassel' },
  
  { name: 'Uni Hamburg', fullName: 'University of Hamburg', country: 'DE', city: 'Hamburg' },
  { name: 'HAW Hamburg', fullName: 'Hamburg University of Applied Sciences', country: 'DE', city: 'Hamburg' },
  { name: 'TU Hamburg', fullName: 'Hamburg University of Technology', country: 'DE', city: 'Hamburg' },
  { name: 'HCU Hamburg', fullName: 'HafenCity University Hamburg', country: 'DE', city: 'Hamburg' },
  { name: 'Bucerius Law School', fullName: 'Bucerius Law School', country: 'DE', city: 'Hamburg' },
  { name: 'HSBA', fullName: 'Hamburg School of Business Administration', country: 'DE', city: 'Hamburg' },
  { name: 'Uni Bremen', fullName: 'University of Bremen', country: 'DE', city: 'Bremen' },
  { name: 'HS Bremen', fullName: 'Hochschule Bremen', country: 'DE', city: 'Bremen' },
  { name: 'Jacobs University', fullName: 'Jacobs University Bremen', country: 'DE', city: 'Bremen' },
  { name: 'Uni Oldenburg', fullName: 'Carl von Ossietzky University Oldenburg', country: 'DE', city: 'Oldenburg' },
  { name: 'Uni Hannover', fullName: 'Leibniz University Hannover', country: 'DE', city: 'Hannover' },
  { name: 'MHH', fullName: 'Hannover Medical School', country: 'DE', city: 'Hannover' },
  { name: 'TU Braunschweig', fullName: 'Technical University of Braunschweig', country: 'DE', city: 'Braunschweig' },
  { name: 'Uni Göttingen', fullName: 'University of Göttingen', country: 'DE', city: 'Göttingen' },
  { name: 'Uni Osnabrück', fullName: 'University of Osnabrück', country: 'DE', city: 'Osnabrück' },
  
  { name: 'TU Dresden', fullName: 'TU Dresden', country: 'DE', city: 'Dresden' },
  { name: 'HTW Dresden', fullName: 'Hochschule für Technik und Wirtschaft Dresden', country: 'DE', city: 'Dresden' },
  { name: 'Uni Leipzig', fullName: 'University of Leipzig', country: 'DE', city: 'Leipzig' },
  { name: 'HTWK Leipzig', fullName: 'Hochschule für Technik, Wirtschaft und Kultur Leipzig', country: 'DE', city: 'Leipzig' },
  { name: 'HHL Leipzig', fullName: 'HHL Leipzig Graduate School of Management', country: 'DE', city: 'Leipzig' },
  { name: 'Uni Jena', fullName: 'Friedrich Schiller University Jena', country: 'DE', city: 'Jena' },
  { name: 'TU Chemnitz', fullName: 'Chemnitz University of Technology', country: 'DE', city: 'Chemnitz' },
  { name: 'TU Freiberg', fullName: 'TU Bergakademie Freiberg', country: 'DE', city: 'Freiberg' },
  { name: 'Uni Halle', fullName: 'Martin Luther University Halle-Wittenberg', country: 'DE', city: 'Halle' },
  { name: 'Uni Magdeburg', fullName: 'Otto von Guericke University Magdeburg', country: 'DE', city: 'Magdeburg' },
  { name: 'Uni Rostock', fullName: 'University of Rostock', country: 'DE', city: 'Rostock' },
  { name: 'Uni Greifswald', fullName: 'University of Greifswald', country: 'DE', city: 'Greifswald' },
  
  { name: 'ETH Zürich', fullName: 'ETH Zurich', country: 'CH', city: 'Zurich' },
  { name: 'Uni Zürich', fullName: 'University of Zurich', country: 'CH', city: 'Zurich' },
  { name: 'UZH', fullName: 'University of Zurich', country: 'CH', city: 'Zurich' },
  { name: 'ZHAW', fullName: 'Zurich University of Applied Sciences', country: 'CH', city: 'Zurich' },
  { name: 'EPFL', fullName: 'École Polytechnique Fédérale de Lausanne', country: 'CH', city: 'Lausanne' },
  { name: 'Uni Lausanne', fullName: 'University of Lausanne', country: 'CH', city: 'Lausanne' },
  { name: 'Uni Genf', fullName: 'University of Geneva', country: 'CH', city: 'Geneva' },
  { name: 'Uni Basel', fullName: 'University of Basel', country: 'CH', city: 'Basel' },
  { name: 'Uni Bern', fullName: 'University of Bern', country: 'CH', city: 'Bern' },
  { name: 'Uni St. Gallen', fullName: 'University of St. Gallen', country: 'CH', city: 'St. Gallen' },
  { name: 'HSG', fullName: 'University of St. Gallen', country: 'CH', city: 'St. Gallen' },
  { name: 'Uni Fribourg', fullName: 'University of Fribourg', country: 'CH', city: 'Fribourg' },
  { name: 'Uni Luzern', fullName: 'University of Lucerne', country: 'CH', city: 'Lucerne' },
  
  { name: 'Uni Wien', fullName: 'University of Vienna', country: 'AT', city: 'Vienna' },
  { name: 'TU Wien', fullName: 'TU Wien', country: 'AT', city: 'Vienna' },
  { name: 'WU Wien', fullName: 'Vienna University of Economics and Business', country: 'AT', city: 'Vienna' },
  { name: 'BOKU', fullName: 'University of Natural Resources and Life Sciences Vienna', country: 'AT', city: 'Vienna' },
  { name: 'MedUni Wien', fullName: 'Medical University of Vienna', country: 'AT', city: 'Vienna' },
  { name: 'Uni Innsbruck', fullName: 'University of Innsbruck', country: 'AT', city: 'Innsbruck' },
  { name: 'Uni Graz', fullName: 'University of Graz', country: 'AT', city: 'Graz' },
  { name: 'TU Graz', fullName: 'Graz University of Technology', country: 'AT', city: 'Graz' },
  { name: 'Uni Salzburg', fullName: 'University of Salzburg', country: 'AT', city: 'Salzburg' },
  { name: 'JKU Linz', fullName: 'Johannes Kepler University Linz', country: 'AT', city: 'Linz' },
  
  { name: 'UvA', fullName: 'University of Amsterdam', country: 'NL', city: 'Amsterdam' },
  { name: 'VU Amsterdam', fullName: 'Vrije Universiteit Amsterdam', country: 'NL', city: 'Amsterdam' },
  { name: 'TU Delft', fullName: 'Delft University of Technology', country: 'NL', city: 'Delft' },
  { name: 'Leiden University', fullName: 'Leiden University', country: 'NL', city: 'Leiden' },
  { name: 'Utrecht University', fullName: 'Utrecht University', country: 'NL', city: 'Utrecht' },
  { name: 'Erasmus University', fullName: 'Erasmus University Rotterdam', country: 'NL', city: 'Rotterdam' },
  { name: 'TU Eindhoven', fullName: 'Eindhoven University of Technology', country: 'NL', city: 'Eindhoven' },
  { name: 'Uni Groningen', fullName: 'University of Groningen', country: 'NL', city: 'Groningen' },
  { name: 'Maastricht University', fullName: 'Maastricht University', country: 'NL', city: 'Maastricht' },
  { name: 'Wageningen University', fullName: 'Wageningen University', country: 'NL', city: 'Wageningen' },
  
  { name: 'KU Leuven', fullName: 'KU Leuven', country: 'BE', city: 'Leuven' },
  { name: 'ULB', fullName: 'Université libre de Bruxelles', country: 'BE', city: 'Brussels' },
  { name: 'Ghent University', fullName: 'Ghent University', country: 'BE', city: 'Ghent' },
  { name: 'UCLouvain', fullName: 'Université catholique de Louvain', country: 'BE', city: 'Louvain-la-Neuve' },
  
  { name: 'Sorbonne', fullName: 'Sorbonne University', country: 'FR', city: 'Paris' },
  { name: 'École Polytechnique', fullName: 'École Polytechnique', country: 'FR', city: 'Palaiseau' },
  { name: 'Sciences Po', fullName: 'Sciences Po Paris', country: 'FR', city: 'Paris' },
  { name: 'ENS Paris', fullName: 'École Normale Supérieure Paris', country: 'FR', city: 'Paris' },
  { name: 'HEC Paris', fullName: 'HEC Paris', country: 'FR', city: 'Paris' },
  { name: 'INSEAD', fullName: 'INSEAD', country: 'FR', city: 'Fontainebleau' },
  { name: 'Uni Paris-Saclay', fullName: 'Université Paris-Saclay', country: 'FR', city: 'Paris' },
  { name: 'PSL', fullName: 'Paris Sciences et Lettres', country: 'FR', city: 'Paris' },
  { name: 'Uni Grenoble', fullName: 'Université Grenoble Alpes', country: 'FR', city: 'Grenoble' },
  { name: 'Uni Lyon', fullName: 'Université de Lyon', country: 'FR', city: 'Lyon' },
  { name: 'Uni Toulouse', fullName: 'Université de Toulouse', country: 'FR', city: 'Toulouse' },
  { name: 'Uni Bordeaux', fullName: 'University of Bordeaux', country: 'FR', city: 'Bordeaux' },
  { name: 'Uni Strasbourg', fullName: 'University of Strasbourg', country: 'FR', city: 'Strasbourg' },
  { name: 'EDHEC', fullName: 'EDHEC Business School', country: 'FR', city: 'Lille' },
  { name: 'ESSEC', fullName: 'ESSEC Business School', country: 'FR', city: 'Cergy' },
  
  { name: 'Oxford', fullName: 'University of Oxford', country: 'GB', city: 'Oxford' },
  { name: 'Cambridge', fullName: 'University of Cambridge', country: 'GB', city: 'Cambridge' },
  { name: 'Imperial', fullName: 'Imperial College London', country: 'GB', city: 'London' },
  { name: 'UCL', fullName: 'University College London', country: 'GB', city: 'London' },
  { name: 'LSE', fullName: 'London School of Economics', country: 'GB', city: 'London' },
  { name: 'Edinburgh', fullName: 'University of Edinburgh', country: 'GB', city: 'Edinburgh' },
  { name: 'KCL', fullName: "King's College London", country: 'GB', city: 'London' },
  { name: 'Manchester', fullName: 'University of Manchester', country: 'GB', city: 'Manchester' },
  { name: 'Warwick', fullName: 'University of Warwick', country: 'GB', city: 'Coventry' },
  { name: 'Bristol', fullName: 'University of Bristol', country: 'GB', city: 'Bristol' },
  { name: 'Glasgow', fullName: 'University of Glasgow', country: 'GB', city: 'Glasgow' },
  { name: 'Durham', fullName: 'Durham University', country: 'GB', city: 'Durham' },
  { name: 'St Andrews', fullName: 'University of St Andrews', country: 'GB', city: 'St Andrews' },
  { name: 'Birmingham', fullName: 'University of Birmingham', country: 'GB', city: 'Birmingham' },
  { name: 'Leeds', fullName: 'University of Leeds', country: 'GB', city: 'Leeds' },
  { name: 'Nottingham', fullName: 'University of Nottingham', country: 'GB', city: 'Nottingham' },
  { name: 'Southampton', fullName: 'University of Southampton', country: 'GB', city: 'Southampton' },
  { name: 'Sheffield', fullName: 'University of Sheffield', country: 'GB', city: 'Sheffield' },
  
  { name: 'Bocconi', fullName: 'Bocconi University', country: 'IT', city: 'Milan' },
  { name: 'Politecnico Milano', fullName: 'Polytechnic University of Milan', country: 'IT', city: 'Milan' },
  { name: 'Uni Bologna', fullName: 'University of Bologna', country: 'IT', city: 'Bologna' },
  { name: 'Sapienza', fullName: 'Sapienza University of Rome', country: 'IT', city: 'Rome' },
  { name: 'Politecnico Torino', fullName: 'Polytechnic University of Turin', country: 'IT', city: 'Turin' },
  { name: 'Uni Padova', fullName: 'University of Padua', country: 'IT', city: 'Padua' },
  { name: 'Uni Milano', fullName: 'University of Milan', country: 'IT', city: 'Milan' },
  { name: 'Uni Pisa', fullName: 'University of Pisa', country: 'IT', city: 'Pisa' },
  { name: 'Uni Firenze', fullName: 'University of Florence', country: 'IT', city: 'Florence' },
  
  { name: 'UB Barcelona', fullName: 'University of Barcelona', country: 'ES', city: 'Barcelona' },
  { name: 'UAM', fullName: 'Autonomous University of Madrid', country: 'ES', city: 'Madrid' },
  { name: 'Complutense', fullName: 'Complutense University of Madrid', country: 'ES', city: 'Madrid' },
  { name: 'UPC', fullName: 'Polytechnic University of Catalonia', country: 'ES', city: 'Barcelona' },
  { name: 'UC3M', fullName: 'Carlos III University of Madrid', country: 'ES', city: 'Madrid' },
  { name: 'Uni Valencia', fullName: 'University of Valencia', country: 'ES', city: 'Valencia' },
  { name: 'IE Business School', fullName: 'IE Business School', country: 'ES', city: 'Madrid' },
  { name: 'ESADE', fullName: 'ESADE Business School', country: 'ES', city: 'Barcelona' },
  
  { name: 'Uni Lisbon', fullName: 'University of Lisbon', country: 'PT', city: 'Lisbon' },
  { name: 'Uni Porto', fullName: 'University of Porto', country: 'PT', city: 'Porto' },
  { name: 'Nova Lisbon', fullName: 'Nova University Lisbon', country: 'PT', city: 'Lisbon' },
  
  { name: 'KTH', fullName: 'KTH Royal Institute of Technology', country: 'SE', city: 'Stockholm' },
  { name: 'Lund University', fullName: 'Lund University', country: 'SE', city: 'Lund' },
  { name: 'Uppsala University', fullName: 'Uppsala University', country: 'SE', city: 'Uppsala' },
  { name: 'Stockholm University', fullName: 'Stockholm University', country: 'SE', city: 'Stockholm' },
  { name: 'Chalmers', fullName: 'Chalmers University of Technology', country: 'SE', city: 'Gothenburg' },
  { name: 'Karolinska', fullName: 'Karolinska Institute', country: 'SE', city: 'Stockholm' },
  
  { name: 'DTU', fullName: 'Technical University of Denmark', country: 'DK', city: 'Copenhagen' },
  { name: 'UCPH', fullName: 'University of Copenhagen', country: 'DK', city: 'Copenhagen' },
  { name: 'Aarhus University', fullName: 'Aarhus University', country: 'DK', city: 'Aarhus' },
  { name: 'CBS', fullName: 'Copenhagen Business School', country: 'DK', city: 'Copenhagen' },
  
  { name: 'Oslo University', fullName: 'University of Oslo', country: 'NO', city: 'Oslo' },
  { name: 'NTNU', fullName: 'Norwegian University of Science and Technology', country: 'NO', city: 'Trondheim' },
  { name: 'Bergen University', fullName: 'University of Bergen', country: 'NO', city: 'Bergen' },
  { name: 'BI Oslo', fullName: 'BI Norwegian Business School', country: 'NO', city: 'Oslo' },
  
  { name: 'Aalto', fullName: 'Aalto University', country: 'FI', city: 'Helsinki' },
  { name: 'Helsinki University', fullName: 'University of Helsinki', country: 'FI', city: 'Helsinki' },
  
  { name: 'UW Warsaw', fullName: 'University of Warsaw', country: 'PL', city: 'Warsaw' },
  { name: 'Jagiellonian', fullName: 'Jagiellonian University', country: 'PL', city: 'Krakow' },
  { name: 'Warsaw Tech', fullName: 'Warsaw University of Technology', country: 'PL', city: 'Warsaw' },
  { name: 'AGH Krakow', fullName: 'AGH University of Science and Technology', country: 'PL', city: 'Krakow' },
  
  { name: 'Charles University', fullName: 'Charles University', country: 'CZ', city: 'Prague' },
  { name: 'CTU Prague', fullName: 'Czech Technical University in Prague', country: 'CZ', city: 'Prague' },
  { name: 'Masaryk University', fullName: 'Masaryk University', country: 'CZ', city: 'Brno' },
  
  { name: 'Eötvös Loránd', fullName: 'Eötvös Loránd University', country: 'HU', city: 'Budapest' },
  { name: 'BME', fullName: 'Budapest University of Technology and Economics', country: 'HU', city: 'Budapest' },
  
  { name: 'TU Dublin', fullName: 'Trinity College Dublin', country: 'IE', city: 'Dublin' },
  { name: 'UCD', fullName: 'University College Dublin', country: 'IE', city: 'Dublin' },
  { name: 'NUI Galway', fullName: 'University of Galway', country: 'IE', city: 'Galway' },
  
  { name: 'HS München', fullName: 'Hochschule München', country: 'DE', city: 'Munich' },
  { name: 'HS Coburg', fullName: 'Hochschule Coburg', country: 'DE', city: 'Coburg' },
  { name: 'HS Hof', fullName: 'Hochschule Hof', country: 'DE', city: 'Hof' },
  { name: 'HS Ansbach', fullName: 'Hochschule Ansbach', country: 'DE', city: 'Ansbach' },
  { name: 'HS Aschaffenburg', fullName: 'Hochschule Aschaffenburg', country: 'DE', city: 'Aschaffenburg' },
  { name: 'HS Amberg-Weiden', fullName: 'Ostbayerische Technische Hochschule Amberg-Weiden', country: 'DE', city: 'Amberg' },
  { name: 'HS Deggendorf', fullName: 'Technische Hochschule Deggendorf', country: 'DE', city: 'Deggendorf' },
  { name: 'Catholic University Eichstätt', fullName: 'Katholische Universität Eichstätt-Ingolstadt', country: 'DE', city: 'Eichstätt' },
  { name: 'Bamberg University', fullName: 'Otto-Friedrich-Universität Bamberg', country: 'DE', city: 'Bamberg' },
  
  { name: 'HS Esslingen', fullName: 'Hochschule Esslingen', country: 'DE', city: 'Esslingen' },
  { name: 'HS Heilbronn', fullName: 'Hochschule Heilbronn', country: 'DE', city: 'Heilbronn' },
  { name: 'HS Offenburg', fullName: 'Hochschule Offenburg', country: 'DE', city: 'Offenburg' },
  { name: 'HS Furtwangen', fullName: 'Hochschule Furtwangen University', country: 'DE', city: 'Furtwangen' },
  { name: 'HS Ravensburg-Weingarten', fullName: 'Hochschule Ravensburg-Weingarten', country: 'DE', city: 'Ravensburg' },
  { name: 'HS Albstadt-Sigmaringen', fullName: 'Hochschule Albstadt-Sigmaringen', country: 'DE', city: 'Albstadt' },
  { name: 'HS Aalen', fullName: 'Hochschule Aalen', country: 'DE', city: 'Aalen' },
  { name: 'Zeppelin University', fullName: 'Zeppelin University', country: 'DE', city: 'Friedrichshafen' },
  
  { name: 'HS Rhein-Main', fullName: 'Hochschule RheinMain', country: 'DE', city: 'Wiesbaden' },
  { name: 'HS Fulda', fullName: 'Hochschule Fulda', country: 'DE', city: 'Fulda' },
  { name: 'HS Wiesbaden', fullName: 'Hochschule RheinMain Wiesbaden', country: 'DE', city: 'Wiesbaden' },
  { name: 'EBS Wiesbaden', fullName: 'EBS Universität für Wirtschaft und Recht', country: 'DE', city: 'Wiesbaden' },
  { name: 'Frankfurt UAS', fullName: 'Frankfurt University of Applied Sciences', country: 'DE', city: 'Frankfurt' },
  { name: 'Provadis HS', fullName: 'Provadis Hochschule', country: 'DE', city: 'Frankfurt' },
  { name: 'WHU', fullName: 'WHU - Otto Beisheim School of Management', country: 'DE', city: 'Vallendar' },
  { name: 'Uni Koblenz', fullName: 'University of Koblenz', country: 'DE', city: 'Koblenz' },
  { name: 'HS Koblenz', fullName: 'Hochschule Koblenz', country: 'DE', city: 'Koblenz' },
  { name: 'Uni Trier', fullName: 'University of Trier', country: 'DE', city: 'Trier' },
  { name: 'HS Trier', fullName: 'Hochschule Trier', country: 'DE', city: 'Trier' },
  
  { name: 'Uni des Saarlandes', fullName: 'Saarland University', country: 'DE', city: 'Saarbrücken' },
  { name: 'HTW Saarland', fullName: 'Hochschule für Technik und Wirtschaft des Saarlandes', country: 'DE', city: 'Saarbrücken' },
  { name: 'DFKI', fullName: 'German Research Center for Artificial Intelligence', country: 'DE', city: 'Saarbrücken' },
  
  { name: 'Hochschule Niederrhein', fullName: 'Hochschule Niederrhein', country: 'DE', city: 'Krefeld' },
  { name: 'HS Ruhr West', fullName: 'Hochschule Ruhr West', country: 'DE', city: 'Mülheim' },
  { name: 'Uni Witten/Herdecke', fullName: 'Witten/Herdecke University', country: 'DE', city: 'Witten' },
  { name: 'FOM', fullName: 'FOM University of Applied Sciences', country: 'DE', city: 'Essen' },
  { name: 'ISM', fullName: 'International School of Management', country: 'DE', city: 'Dortmund' },
  { name: 'CBS Cologne', fullName: 'Cologne Business School', country: 'DE', city: 'Cologne' },
  { name: 'HS Hamm-Lippstadt', fullName: 'Hochschule Hamm-Lippstadt', country: 'DE', city: 'Hamm' },
  { name: 'Uni Paderborn', fullName: 'Paderborn University', country: 'DE', city: 'Paderborn' },
  
  { name: 'Uni Hildesheim', fullName: 'University of Hildesheim', country: 'DE', city: 'Hildesheim' },
  { name: 'Leuphana Lüneburg', fullName: 'Leuphana University of Lüneburg', country: 'DE', city: 'Lüneburg' },
  { name: 'TU Clausthal', fullName: 'Clausthal University of Technology', country: 'DE', city: 'Clausthal-Zellerfeld' },
  { name: 'Uni Vechta', fullName: 'University of Vechta', country: 'DE', city: 'Vechta' },
  { name: 'HS Osnabrück', fullName: 'Hochschule Osnabrück', country: 'DE', city: 'Osnabrück' },
  { name: 'HS Emden/Leer', fullName: 'Hochschule Emden/Leer', country: 'DE', city: 'Emden' },
  { name: 'Jade HS', fullName: 'Jade Hochschule', country: 'DE', city: 'Wilhelmshaven' },
  
  { name: 'Uni Erfurt', fullName: 'University of Erfurt', country: 'DE', city: 'Erfurt' },
  { name: 'Bauhaus Weimar', fullName: 'Bauhaus University Weimar', country: 'DE', city: 'Weimar' },
  { name: 'HS Schmalkalden', fullName: 'Hochschule Schmalkalden', country: 'DE', city: 'Schmalkalden' },
  { name: 'HS Nordhausen', fullName: 'Hochschule Nordhausen', country: 'DE', city: 'Nordhausen' },
  { name: 'EAH Jena', fullName: 'Ernst-Abbe-Hochschule Jena', country: 'DE', city: 'Jena' },
  
  { name: 'Uni Kiel', fullName: 'Kiel University', country: 'DE', city: 'Kiel' },
  { name: 'Uni Lübeck', fullName: 'University of Lübeck', country: 'DE', city: 'Lübeck' },
  { name: 'Uni Flensburg', fullName: 'Europa-Universität Flensburg', country: 'DE', city: 'Flensburg' },
  { name: 'FH Kiel', fullName: 'Fachhochschule Kiel', country: 'DE', city: 'Kiel' },
  { name: 'TH Lübeck', fullName: 'Technische Hochschule Lübeck', country: 'DE', city: 'Lübeck' },
  { name: 'HS Flensburg', fullName: 'Hochschule Flensburg', country: 'DE', city: 'Flensburg' },
  
  { name: 'Uni Zittau', fullName: 'Zittau/Görlitz University of Applied Sciences', country: 'DE', city: 'Zittau' },
  { name: 'HS Mittweida', fullName: 'Hochschule Mittweida', country: 'DE', city: 'Mittweida' },
  { name: 'HS Zwickau', fullName: 'Westsächsische Hochschule Zwickau', country: 'DE', city: 'Zwickau' },
  { name: 'HTWK Leipzig', fullName: 'Hochschule für Technik, Wirtschaft und Kultur Leipzig', country: 'DE', city: 'Leipzig' },
  
  { name: 'Uni Stralsund', fullName: 'Hochschule Stralsund', country: 'DE', city: 'Stralsund' },
  { name: 'Uni Wismar', fullName: 'Hochschule Wismar', country: 'DE', city: 'Wismar' },
  { name: 'Uni Neubrandenburg', fullName: 'Hochschule Neubrandenburg', country: 'DE', city: 'Neubrandenburg' },
  
  { name: 'BTU Cottbus', fullName: 'Brandenburg University of Technology Cottbus-Senftenberg', country: 'DE', city: 'Cottbus' },
  { name: 'Viadrina', fullName: 'European University Viadrina', country: 'DE', city: 'Frankfurt (Oder)' },
  { name: 'TH Brandenburg', fullName: 'Technische Hochschule Brandenburg', country: 'DE', city: 'Brandenburg' },
  { name: 'TH Wildau', fullName: 'Technische Hochschule Wildau', country: 'DE', city: 'Wildau' },
  
  { name: 'Hertie School', fullName: 'Hertie School', country: 'DE', city: 'Berlin' },
  { name: 'ESMT Berlin', fullName: 'ESMT Berlin', country: 'DE', city: 'Berlin' },
  { name: 'CODE University', fullName: 'CODE University of Applied Sciences', country: 'DE', city: 'Berlin' },
  { name: 'SRH Berlin', fullName: 'SRH Hochschule Berlin', country: 'DE', city: 'Berlin' },
  { name: 'bbw HS', fullName: 'bbw Hochschule', country: 'DE', city: 'Berlin' },
  { name: 'HMKW Berlin', fullName: 'HMKW Hochschule für Medien', country: 'DE', city: 'Berlin' },
  { name: 'UdK Berlin', fullName: 'Berlin University of the Arts', country: 'DE', city: 'Berlin' },
  
  { name: 'EuroFH', fullName: 'Europäische Fernhochschule Hamburg', country: 'DE', city: 'Hamburg' },
  { name: 'Kühne Logistics', fullName: 'Kühne Logistics University', country: 'DE', city: 'Hamburg' },
  { name: 'MSH Hamburg', fullName: 'Medical School Hamburg', country: 'DE', city: 'Hamburg' },
  { name: 'HS Fresenius Hamburg', fullName: 'Hochschule Fresenius Hamburg', country: 'DE', city: 'Hamburg' },
  
  { name: 'Constructor University', fullName: 'Constructor University Bremen', country: 'DE', city: 'Bremen' },
  { name: 'HS Bremerhaven', fullName: 'Hochschule Bremerhaven', country: 'DE', city: 'Bremerhaven' },
  
  { name: 'Geneva Business School', fullName: 'Geneva Business School', country: 'CH', city: 'Geneva' },
  { name: 'Uni Neuchâtel', fullName: 'University of Neuchâtel', country: 'CH', city: 'Neuchâtel' },
  { name: 'USI', fullName: 'Università della Svizzera italiana', country: 'CH', city: 'Lugano' },
  { name: 'ZHAW Winterthur', fullName: 'ZHAW Zurich University of Applied Sciences', country: 'CH', city: 'Winterthur' },
  { name: 'FHNW', fullName: 'University of Applied Sciences Northwestern Switzerland', country: 'CH', city: 'Basel' },
  { name: 'HES-SO', fullName: 'University of Applied Sciences Western Switzerland', country: 'CH', city: 'Lausanne' },
  { name: 'SUPSI', fullName: 'University of Applied Sciences of Southern Switzerland', country: 'CH', city: 'Lugano' },
  
  { name: 'Uni Klagenfurt', fullName: 'University of Klagenfurt', country: 'AT', city: 'Klagenfurt' },
  { name: 'FH Wien', fullName: 'FH Wien der WKW', country: 'AT', city: 'Vienna' },
  { name: 'FHWien', fullName: 'University of Applied Sciences Technikum Wien', country: 'AT', city: 'Vienna' },
  { name: 'FH Vorarlberg', fullName: 'FH Vorarlberg', country: 'AT', city: 'Dornbirn' },
  { name: 'FH Salzburg', fullName: 'Salzburg University of Applied Sciences', country: 'AT', city: 'Salzburg' },
  { name: 'FH Oberösterreich', fullName: 'University of Applied Sciences Upper Austria', country: 'AT', city: 'Linz' },
  { name: 'MCI Innsbruck', fullName: 'MCI Management Center Innsbruck', country: 'AT', city: 'Innsbruck' },
  { name: 'Webster Vienna', fullName: 'Webster University Vienna', country: 'AT', city: 'Vienna' },
  { name: 'Modul University', fullName: 'MODUL University Vienna', country: 'AT', city: 'Vienna' },
  
  { name: 'Rotterdam School', fullName: 'Rotterdam School of Management', country: 'NL', city: 'Rotterdam' },
  { name: 'Tilburg University', fullName: 'Tilburg University', country: 'NL', city: 'Tilburg' },
  { name: 'Radboud University', fullName: 'Radboud University Nijmegen', country: 'NL', city: 'Nijmegen' },
  { name: 'Twente University', fullName: 'University of Twente', country: 'NL', city: 'Enschede' },
  { name: 'VU Amsterdam', fullName: 'Vrije Universiteit Amsterdam', country: 'NL', city: 'Amsterdam' },
  { name: 'HAN', fullName: 'HAN University of Applied Sciences', country: 'NL', city: 'Arnhem' },
  { name: 'Fontys', fullName: 'Fontys University of Applied Sciences', country: 'NL', city: 'Eindhoven' },
  { name: 'Amsterdam UAS', fullName: 'Amsterdam University of Applied Sciences', country: 'NL', city: 'Amsterdam' },
  { name: 'The Hague UAS', fullName: 'The Hague University of Applied Sciences', country: 'NL', city: 'The Hague' },
  
  { name: 'VUB', fullName: 'Vrije Universiteit Brussel', country: 'BE', city: 'Brussels' },
  { name: 'Antwerp University', fullName: 'University of Antwerp', country: 'BE', city: 'Antwerp' },
  { name: 'ULiège', fullName: 'University of Liège', country: 'BE', city: 'Liège' },
  { name: 'UMons', fullName: 'University of Mons', country: 'BE', city: 'Mons' },
  { name: 'UNamur', fullName: 'University of Namur', country: 'BE', city: 'Namur' },
  { name: 'Hasselt University', fullName: 'Hasselt University', country: 'BE', city: 'Hasselt' },
  
  { name: 'Paris Dauphine', fullName: 'Université Paris-Dauphine', country: 'FR', city: 'Paris' },
  { name: 'CentraleSupélec', fullName: 'CentraleSupélec', country: 'FR', city: 'Paris' },
  { name: 'Mines Paris', fullName: 'Mines Paris - PSL', country: 'FR', city: 'Paris' },
  { name: 'Télécom Paris', fullName: 'Télécom Paris', country: 'FR', city: 'Paris' },
  { name: 'Ponts ParisTech', fullName: 'École des Ponts ParisTech', country: 'FR', city: 'Paris' },
  { name: 'AgroParisTech', fullName: 'AgroParisTech', country: 'FR', city: 'Paris' },
  { name: 'ESCP', fullName: 'ESCP Business School', country: 'FR', city: 'Paris' },
  { name: 'EMLYON', fullName: 'EMLYON Business School', country: 'FR', city: 'Lyon' },
  { name: 'Grenoble EM', fullName: 'Grenoble École de Management', country: 'FR', city: 'Grenoble' },
  { name: 'Skema', fullName: 'SKEMA Business School', country: 'FR', city: 'Sophia Antipolis' },
  { name: 'Audencia', fullName: 'Audencia Business School', country: 'FR', city: 'Nantes' },
  { name: 'TBS Education', fullName: 'TBS Education', country: 'FR', city: 'Toulouse' },
  { name: 'NEOMA', fullName: 'NEOMA Business School', country: 'FR', city: 'Reims' },
  { name: 'Rennes School', fullName: 'Rennes School of Business', country: 'FR', city: 'Rennes' },
  { name: 'Kedge', fullName: 'KEDGE Business School', country: 'FR', city: 'Marseille' },
  { name: 'Montpellier BS', fullName: 'Montpellier Business School', country: 'FR', city: 'Montpellier' },
  { name: 'Uni Aix-Marseille', fullName: 'Aix-Marseille University', country: 'FR', city: 'Marseille' },
  { name: 'Uni Lille', fullName: 'University of Lille', country: 'FR', city: 'Lille' },
  { name: 'Uni Nantes', fullName: 'University of Nantes', country: 'FR', city: 'Nantes' },
  { name: 'Uni Rennes', fullName: 'University of Rennes', country: 'FR', city: 'Rennes' },
  { name: 'Uni Nice', fullName: 'Université Côte d\'Azur', country: 'FR', city: 'Nice' },
  { name: 'Uni Montpellier', fullName: 'University of Montpellier', country: 'FR', city: 'Montpellier' },
  
  { name: 'York University', fullName: 'University of York', country: 'GB', city: 'York' },
  { name: 'Lancaster', fullName: 'Lancaster University', country: 'GB', city: 'Lancaster' },
  { name: 'Bath', fullName: 'University of Bath', country: 'GB', city: 'Bath' },
  { name: 'Loughborough', fullName: 'Loughborough University', country: 'GB', city: 'Loughborough' },
  { name: 'Sussex', fullName: 'University of Sussex', country: 'GB', city: 'Brighton' },
  { name: 'Surrey', fullName: 'University of Surrey', country: 'GB', city: 'Guildford' },
  { name: 'Exeter', fullName: 'University of Exeter', country: 'GB', city: 'Exeter' },
  { name: 'Leicester', fullName: 'University of Leicester', country: 'GB', city: 'Leicester' },
  { name: 'Liverpool', fullName: 'University of Liverpool', country: 'GB', city: 'Liverpool' },
  { name: 'Queen Mary', fullName: 'Queen Mary University of London', country: 'GB', city: 'London' },
  { name: 'City London', fullName: 'City, University of London', country: 'GB', city: 'London' },
  { name: 'Royal Holloway', fullName: 'Royal Holloway, University of London', country: 'GB', city: 'London' },
  { name: 'SOAS', fullName: 'SOAS University of London', country: 'GB', city: 'London' },
  { name: 'Brunel', fullName: 'Brunel University London', country: 'GB', city: 'London' },
  { name: 'Cranfield', fullName: 'Cranfield University', country: 'GB', city: 'Cranfield' },
  { name: 'Reading', fullName: 'University of Reading', country: 'GB', city: 'Reading' },
  { name: 'Essex', fullName: 'University of Essex', country: 'GB', city: 'Colchester' },
  { name: 'Kent', fullName: 'University of Kent', country: 'GB', city: 'Canterbury' },
  { name: 'Aberdeen', fullName: 'University of Aberdeen', country: 'GB', city: 'Aberdeen' },
  { name: 'Strathclyde', fullName: 'University of Strathclyde', country: 'GB', city: 'Glasgow' },
  { name: 'Heriot-Watt', fullName: 'Heriot-Watt University', country: 'GB', city: 'Edinburgh' },
  { name: 'Dundee', fullName: 'University of Dundee', country: 'GB', city: 'Dundee' },
  { name: 'Cardiff', fullName: 'Cardiff University', country: 'GB', city: 'Cardiff' },
  { name: 'Swansea', fullName: 'Swansea University', country: 'GB', city: 'Swansea' },
  { name: "Queen's Belfast", fullName: "Queen's University Belfast", country: 'GB', city: 'Belfast' },
  { name: 'Ulster', fullName: 'Ulster University', country: 'GB', city: 'Belfast' },
  
  { name: 'Uni Roma Tre', fullName: 'Roma Tre University', country: 'IT', city: 'Rome' },
  { name: 'Tor Vergata', fullName: 'University of Rome Tor Vergata', country: 'IT', city: 'Rome' },
  { name: 'Uni Napoli', fullName: 'University of Naples Federico II', country: 'IT', city: 'Naples' },
  { name: 'Uni Torino', fullName: 'University of Turin', country: 'IT', city: 'Turin' },
  { name: 'Uni Genova', fullName: 'University of Genoa', country: 'IT', city: 'Genoa' },
  { name: 'Uni Parma', fullName: 'University of Parma', country: 'IT', city: 'Parma' },
  { name: 'Uni Modena', fullName: 'University of Modena and Reggio Emilia', country: 'IT', city: 'Modena' },
  { name: 'Uni Ferrara', fullName: 'University of Ferrara', country: 'IT', city: 'Ferrara' },
  { name: 'Uni Siena', fullName: 'University of Siena', country: 'IT', city: 'Siena' },
  { name: 'Uni Perugia', fullName: 'University of Perugia', country: 'IT', city: 'Perugia' },
  { name: 'Uni Trento', fullName: 'University of Trento', country: 'IT', city: 'Trento' },
  { name: 'Uni Trieste', fullName: 'University of Trieste', country: 'IT', city: 'Trieste' },
  { name: 'Uni Verona', fullName: 'University of Verona', country: 'IT', city: 'Verona' },
  { name: 'Uni Venezia', fullName: 'Ca\' Foscari University of Venice', country: 'IT', city: 'Venice' },
  { name: 'Uni Catania', fullName: 'University of Catania', country: 'IT', city: 'Catania' },
  { name: 'Uni Palermo', fullName: 'University of Palermo', country: 'IT', city: 'Palermo' },
  { name: 'Uni Bari', fullName: 'University of Bari', country: 'IT', city: 'Bari' },
  { name: 'Uni Salento', fullName: 'University of Salento', country: 'IT', city: 'Lecce' },
  
  { name: 'Pompeu Fabra', fullName: 'Pompeu Fabra University', country: 'ES', city: 'Barcelona' },
  { name: 'Uni Granada', fullName: 'University of Granada', country: 'ES', city: 'Granada' },
  { name: 'Uni Sevilla', fullName: 'University of Seville', country: 'ES', city: 'Seville' },
  { name: 'Uni Zaragoza', fullName: 'University of Zaragoza', country: 'ES', city: 'Zaragoza' },
  { name: 'Uni Murcia', fullName: 'University of Murcia', country: 'ES', city: 'Murcia' },
  { name: 'Uni Alicante', fullName: 'University of Alicante', country: 'ES', city: 'Alicante' },
  { name: 'Uni País Vasco', fullName: 'University of the Basque Country', country: 'ES', city: 'Bilbao' },
  { name: 'Uni Santiago', fullName: 'University of Santiago de Compostela', country: 'ES', city: 'Santiago' },
  { name: 'Uni Navarra', fullName: 'University of Navarra', country: 'ES', city: 'Pamplona' },
  { name: 'Ramon Llull', fullName: 'Ramon Llull University', country: 'ES', city: 'Barcelona' },
  { name: 'Deusto', fullName: 'University of Deusto', country: 'ES', city: 'Bilbao' },
  
  { name: 'Uni Coimbra', fullName: 'University of Coimbra', country: 'PT', city: 'Coimbra' },
  { name: 'Uni Minho', fullName: 'University of Minho', country: 'PT', city: 'Braga' },
  { name: 'Uni Aveiro', fullName: 'University of Aveiro', country: 'PT', city: 'Aveiro' },
  { name: 'ISCTE', fullName: 'ISCTE - University Institute of Lisbon', country: 'PT', city: 'Lisbon' },
  
  { name: 'Gothenburg University', fullName: 'University of Gothenburg', country: 'SE', city: 'Gothenburg' },
  { name: 'Linköping University', fullName: 'Linköping University', country: 'SE', city: 'Linköping' },
  { name: 'Umeå University', fullName: 'Umeå University', country: 'SE', city: 'Umeå' },
  { name: 'Örebro University', fullName: 'Örebro University', country: 'SE', city: 'Örebro' },
  { name: 'Malmö University', fullName: 'Malmö University', country: 'SE', city: 'Malmö' },
  { name: 'Stockholm School', fullName: 'Stockholm School of Economics', country: 'SE', city: 'Stockholm' },
  
  { name: 'SDU', fullName: 'University of Southern Denmark', country: 'DK', city: 'Odense' },
  { name: 'Aalborg University', fullName: 'Aalborg University', country: 'DK', city: 'Aalborg' },
  { name: 'Roskilde University', fullName: 'Roskilde University', country: 'DK', city: 'Roskilde' },
  { name: 'IT University', fullName: 'IT University of Copenhagen', country: 'DK', city: 'Copenhagen' },
  
  { name: 'Tromsø University', fullName: 'UiT The Arctic University of Norway', country: 'NO', city: 'Tromsø' },
  { name: 'Stavanger University', fullName: 'University of Stavanger', country: 'NO', city: 'Stavanger' },
  { name: 'Agder University', fullName: 'University of Agder', country: 'NO', city: 'Kristiansand' },
  { name: 'NMBU', fullName: 'Norwegian University of Life Sciences', country: 'NO', city: 'Ås' },
  { name: 'NHH', fullName: 'Norwegian School of Economics', country: 'NO', city: 'Bergen' },
  
  { name: 'Turku University', fullName: 'University of Turku', country: 'FI', city: 'Turku' },
  { name: 'Oulu University', fullName: 'University of Oulu', country: 'FI', city: 'Oulu' },
  { name: 'Jyväskylä University', fullName: 'University of Jyväskylä', country: 'FI', city: 'Jyväskylä' },
  { name: 'Tampere University', fullName: 'Tampere University', country: 'FI', city: 'Tampere' },
  { name: 'LUT', fullName: 'LUT University', country: 'FI', city: 'Lappeenranta' },
  
  { name: 'Wrocław Tech', fullName: 'Wrocław University of Science and Technology', country: 'PL', city: 'Wrocław' },
  { name: 'Uni Wrocław', fullName: 'University of Wrocław', country: 'PL', city: 'Wrocław' },
  { name: 'Poznań Tech', fullName: 'Poznań University of Technology', country: 'PL', city: 'Poznań' },
  { name: 'Adam Mickiewicz', fullName: 'Adam Mickiewicz University', country: 'PL', city: 'Poznań' },
  { name: 'Gdańsk Tech', fullName: 'Gdańsk University of Technology', country: 'PL', city: 'Gdańsk' },
  { name: 'Uni Gdańsk', fullName: 'University of Gdańsk', country: 'PL', city: 'Gdańsk' },
  { name: 'Łódź Tech', fullName: 'Lodz University of Technology', country: 'PL', city: 'Łódź' },
  { name: 'Uni Łódź', fullName: 'University of Łódź', country: 'PL', city: 'Łódź' },
  { name: 'Silesian Tech', fullName: 'Silesian University of Technology', country: 'PL', city: 'Gliwice' },
  { name: 'Kozminski', fullName: 'Kozminski University', country: 'PL', city: 'Warsaw' },
  
  { name: 'Brno Tech', fullName: 'Brno University of Technology', country: 'CZ', city: 'Brno' },
  { name: 'Mendel University', fullName: 'Mendel University in Brno', country: 'CZ', city: 'Brno' },
  { name: 'Palacký University', fullName: 'Palacký University Olomouc', country: 'CZ', city: 'Olomouc' },
  { name: 'University of Economics', fullName: 'Prague University of Economics and Business', country: 'CZ', city: 'Prague' },
  
  { name: 'Corvinus', fullName: 'Corvinus University of Budapest', country: 'HU', city: 'Budapest' },
  { name: 'Semmelweis', fullName: 'Semmelweis University', country: 'HU', city: 'Budapest' },
  { name: 'Uni Szeged', fullName: 'University of Szeged', country: 'HU', city: 'Szeged' },
  { name: 'Uni Debrecen', fullName: 'University of Debrecen', country: 'HU', city: 'Debrecen' },
  { name: 'Uni Pécs', fullName: 'University of Pécs', country: 'HU', city: 'Pécs' },
  
  { name: 'Babeș-Bolyai', fullName: 'Babeș-Bolyai University', country: 'RO', city: 'Cluj-Napoca' },
  { name: 'Uni Bucharest', fullName: 'University of Bucharest', country: 'RO', city: 'Bucharest' },
  { name: 'Politehnica Bucharest', fullName: 'Politehnica University of Bucharest', country: 'RO', city: 'Bucharest' },
  
  { name: 'Ljubljana University', fullName: 'University of Ljubljana', country: 'SI', city: 'Ljubljana' },
  { name: 'Maribor University', fullName: 'University of Maribor', country: 'SI', city: 'Maribor' },
  
  { name: 'Zagreb University', fullName: 'University of Zagreb', country: 'HR', city: 'Zagreb' },
  { name: 'Split University', fullName: 'University of Split', country: 'HR', city: 'Split' },
  
  { name: 'Belgrade University', fullName: 'University of Belgrade', country: 'RS', city: 'Belgrade' },
  { name: 'Novi Sad University', fullName: 'University of Novi Sad', country: 'RS', city: 'Novi Sad' },
  
  { name: 'Sofia University', fullName: 'Sofia University', country: 'BG', city: 'Sofia' },
  { name: 'Sofia Tech', fullName: 'Technical University of Sofia', country: 'BG', city: 'Sofia' },
  
  { name: 'Athens University', fullName: 'National and Kapodistrian University of Athens', country: 'GR', city: 'Athens' },
  { name: 'Aristotle Thessaloniki', fullName: 'Aristotle University of Thessaloniki', country: 'GR', city: 'Thessaloniki' },
  { name: 'Athens Tech', fullName: 'National Technical University of Athens', country: 'GR', city: 'Athens' },
  
  { name: 'UCC', fullName: 'University College Cork', country: 'IE', city: 'Cork' },
  { name: 'UL', fullName: 'University of Limerick', country: 'IE', city: 'Limerick' },
  { name: 'DCU', fullName: 'Dublin City University', country: 'IE', city: 'Dublin' },
  { name: 'RCSI', fullName: 'Royal College of Surgeons in Ireland', country: 'IE', city: 'Dublin' },
  { name: 'TU Dublin', fullName: 'Technological University Dublin', country: 'IE', city: 'Dublin' },
  
  { name: 'MIT', fullName: 'Massachusetts Institute of Technology', country: 'US', city: 'Cambridge' },
  { name: 'Stanford', fullName: 'Stanford University', country: 'US', city: 'Stanford' },
  { name: 'Harvard', fullName: 'Harvard University', country: 'US', city: 'Cambridge' },
  { name: 'UC Berkeley', fullName: 'University of California, Berkeley', country: 'US', city: 'Berkeley' },
  { name: 'Caltech', fullName: 'California Institute of Technology', country: 'US', city: 'Pasadena' },
  { name: 'Princeton', fullName: 'Princeton University', country: 'US', city: 'Princeton' },
  { name: 'Yale', fullName: 'Yale University', country: 'US', city: 'New Haven' },
  { name: 'Columbia', fullName: 'Columbia University', country: 'US', city: 'New York' },
  { name: 'UChicago', fullName: 'University of Chicago', country: 'US', city: 'Chicago' },
  { name: 'UPenn', fullName: 'University of Pennsylvania', country: 'US', city: 'Philadelphia' },
  { name: 'Cornell', fullName: 'Cornell University', country: 'US', city: 'Ithaca' },
  { name: 'Duke', fullName: 'Duke University', country: 'US', city: 'Durham' },
  { name: 'Northwestern', fullName: 'Northwestern University', country: 'US', city: 'Evanston' },
  { name: 'NYU', fullName: 'New York University', country: 'US', city: 'New York' },
  { name: 'UCLA', fullName: 'University of California, Los Angeles', country: 'US', city: 'Los Angeles' },
  { name: 'Carnegie Mellon', fullName: 'Carnegie Mellon University', country: 'US', city: 'Pittsburgh' },
  { name: 'UMich', fullName: 'University of Michigan', country: 'US', city: 'Ann Arbor' },
  { name: 'Georgia Tech', fullName: 'Georgia Institute of Technology', country: 'US', city: 'Atlanta' },
  { name: 'UT Austin', fullName: 'University of Texas at Austin', country: 'US', city: 'Austin' },
  { name: 'UW Seattle', fullName: 'University of Washington', country: 'US', city: 'Seattle' },
  
  { name: 'UofT', fullName: 'University of Toronto', country: 'CA', city: 'Toronto' },
  { name: 'UBC', fullName: 'University of British Columbia', country: 'CA', city: 'Vancouver' },
  { name: 'McGill', fullName: 'McGill University', country: 'CA', city: 'Montreal' },
  { name: 'McMaster', fullName: 'McMaster University', country: 'CA', city: 'Hamilton' },
  { name: 'Waterloo', fullName: 'University of Waterloo', country: 'CA', city: 'Waterloo' },
  { name: 'Western', fullName: 'Western University', country: 'CA', city: 'London' },
  { name: 'Queen\'s', fullName: 'Queen\'s University', country: 'CA', city: 'Kingston' },
  
  { name: 'NUS', fullName: 'National University of Singapore', country: 'SG', city: 'Singapore' },
  { name: 'NTU Singapore', fullName: 'Nanyang Technological University', country: 'SG', city: 'Singapore' },
  { name: 'SMU', fullName: 'Singapore Management University', country: 'SG', city: 'Singapore' },
  
  { name: 'HKU', fullName: 'University of Hong Kong', country: 'HK', city: 'Hong Kong' },
  { name: 'HKUST', fullName: 'Hong Kong University of Science and Technology', country: 'HK', city: 'Hong Kong' },
  { name: 'CUHK', fullName: 'Chinese University of Hong Kong', country: 'HK', city: 'Hong Kong' },
  
  { name: 'Tsinghua', fullName: 'Tsinghua University', country: 'CN', city: 'Beijing' },
  { name: 'Peking University', fullName: 'Peking University', country: 'CN', city: 'Beijing' },
  { name: 'Fudan', fullName: 'Fudan University', country: 'CN', city: 'Shanghai' },
  { name: 'Zhejiang', fullName: 'Zhejiang University', country: 'CN', city: 'Hangzhou' },
  
  { name: 'UTokyo', fullName: 'University of Tokyo', country: 'JP', city: 'Tokyo' },
  { name: 'Kyoto University', fullName: 'Kyoto University', country: 'JP', city: 'Kyoto' },
  { name: 'Osaka University', fullName: 'Osaka University', country: 'JP', city: 'Osaka' },
  { name: 'Tohoku University', fullName: 'Tohoku University', country: 'JP', city: 'Sendai' },
  { name: 'Tokyo Tech', fullName: 'Tokyo Institute of Technology', country: 'JP', city: 'Tokyo' },
  
  { name: 'SNU', fullName: 'Seoul National University', country: 'KR', city: 'Seoul' },
  { name: 'KAIST', fullName: 'Korea Advanced Institute of Science and Technology', country: 'KR', city: 'Daejeon' },
  { name: 'Yonsei', fullName: 'Yonsei University', country: 'KR', city: 'Seoul' },
  { name: 'Korea University', fullName: 'Korea University', country: 'KR', city: 'Seoul' },
  
  { name: 'ANU', fullName: 'Australian National University', country: 'AU', city: 'Canberra' },
  { name: 'UniMelb', fullName: 'University of Melbourne', country: 'AU', city: 'Melbourne' },
  { name: 'USYD', fullName: 'University of Sydney', country: 'AU', city: 'Sydney' },
  { name: 'UNSW', fullName: 'University of New South Wales', country: 'AU', city: 'Sydney' },
  { name: 'UQ', fullName: 'University of Queensland', country: 'AU', city: 'Brisbane' },
  { name: 'Monash', fullName: 'Monash University', country: 'AU', city: 'Melbourne' },
  { name: 'UWA', fullName: 'University of Western Australia', country: 'AU', city: 'Perth' },
  { name: 'Adelaide', fullName: 'University of Adelaide', country: 'AU', city: 'Adelaide' },
  
  { name: 'Boğaziçi', fullName: 'Boğaziçi University', country: 'TR', city: 'Istanbul' },
  { name: 'METU', fullName: 'Middle East Technical University', country: 'TR', city: 'Ankara' },
  { name: 'ODTÜ', fullName: 'Orta Doğu Teknik Üniversitesi', country: 'TR', city: 'Ankara' },
  { name: 'İTÜ', fullName: 'Istanbul Technical University', country: 'TR', city: 'Istanbul' },
  { name: 'Koç University', fullName: 'Koç University', country: 'TR', city: 'Istanbul' },
  { name: 'Sabancı', fullName: 'Sabancı University', country: 'TR', city: 'Istanbul' },
  { name: 'Bilkent', fullName: 'Bilkent University', country: 'TR', city: 'Ankara' },
  { name: 'Istanbul University', fullName: 'Istanbul University', country: 'TR', city: 'Istanbul' },
  { name: 'Ankara University', fullName: 'Ankara University', country: 'TR', city: 'Ankara' },
  { name: 'Hacettepe', fullName: 'Hacettepe University', country: 'TR', city: 'Ankara' },
  { name: 'Gazi University', fullName: 'Gazi University', country: 'TR', city: 'Ankara' },
  { name: 'Ege University', fullName: 'Ege University', country: 'TR', city: 'Izmir' },
  { name: 'Dokuz Eylül', fullName: 'Dokuz Eylül University', country: 'TR', city: 'Izmir' },
  { name: 'İzmir Tech', fullName: 'Izmir Institute of Technology', country: 'TR', city: 'Izmir' },
  { name: 'Yaşar University', fullName: 'Yaşar University', country: 'TR', city: 'Izmir' },
  { name: 'Yıldız Teknik', fullName: 'Yıldız Technical University', country: 'TR', city: 'Istanbul' },
  { name: 'Marmara University', fullName: 'Marmara University', country: 'TR', city: 'Istanbul' },
  { name: 'Galatasaray', fullName: 'Galatasaray University', country: 'TR', city: 'Istanbul' },
  { name: 'Özyeğin', fullName: 'Özyeğin University', country: 'TR', city: 'Istanbul' },
  { name: 'Bahçeşehir', fullName: 'Bahçeşehir University', country: 'TR', city: 'Istanbul' },
  { name: 'Işık University', fullName: 'Işık University', country: 'TR', city: 'Istanbul' },
  { name: 'Kadir Has', fullName: 'Kadir Has University', country: 'TR', city: 'Istanbul' },
  { name: 'İstanbul Bilgi', fullName: 'Istanbul Bilgi University', country: 'TR', city: 'Istanbul' },
  { name: 'Yeditepe', fullName: 'Yeditepe University', country: 'TR', city: 'Istanbul' },
  { name: 'Anadolu University', fullName: 'Anadolu University', country: 'TR', city: 'Eskişehir' },
  { name: 'Uludağ', fullName: 'Uludağ University', country: 'TR', city: 'Bursa' },
  { name: 'Erciyes', fullName: 'Erciyes University', country: 'TR', city: 'Kayseri' },
  { name: 'Selçuk University', fullName: 'Selçuk University', country: 'TR', city: 'Konya' },
  { name: 'Çukurova', fullName: 'Çukurova University', country: 'TR', city: 'Adana' },
  { name: 'Akdeniz', fullName: 'Akdeniz University', country: 'TR', city: 'Antalya' },
  { name: 'Atatürk University', fullName: 'Atatürk University', country: 'TR', city: 'Erzurum' },
  { name: 'Gaziantep University', fullName: 'Gaziantep University', country: 'TR', city: 'Gaziantep' },
  { name: 'Ondokuz Mayıs', fullName: 'Ondokuz Mayıs University', country: 'TR', city: 'Samsun' },
  { name: 'Pamukkale', fullName: 'Pamukkale University', country: 'TR', city: 'Denizli' },
  { name: 'Sakarya University', fullName: 'Sakarya University', country: 'TR', city: 'Sakarya' },
  { name: 'Kocaeli University', fullName: 'Kocaeli University', country: 'TR', city: 'Kocaeli' },
  { name: 'TOBB ETÜ', fullName: 'TOBB University of Economics and Technology', country: 'TR', city: 'Ankara' },
  { name: 'Atılım', fullName: 'Atılım University', country: 'TR', city: 'Ankara' },
  { name: 'Başkent', fullName: 'Başkent University', country: 'TR', city: 'Ankara' },
  { name: 'Çankaya', fullName: 'Çankaya University', country: 'TR', city: 'Ankara' },
  { name: 'TED University', fullName: 'TED University', country: 'TR', city: 'Ankara' },
  
  { name: 'Uni Luxembourg', fullName: 'University of Luxembourg', country: 'LU', city: 'Luxembourg' },
  
  { name: 'Vilnius University', fullName: 'Vilnius University', country: 'LT', city: 'Vilnius' },
  { name: 'Kaunas Tech', fullName: 'Kaunas University of Technology', country: 'LT', city: 'Kaunas' },
  { name: 'Riga Tech', fullName: 'Riga Technical University', country: 'LV', city: 'Riga' },
  { name: 'Uni Latvia', fullName: 'University of Latvia', country: 'LV', city: 'Riga' },
  { name: 'Tallinn Tech', fullName: 'Tallinn University of Technology', country: 'EE', city: 'Tallinn' },
  { name: 'Tartu University', fullName: 'University of Tartu', country: 'EE', city: 'Tartu' },
  
  { name: 'Comenius', fullName: 'Comenius University in Bratislava', country: 'SK', city: 'Bratislava' },
  { name: 'Slovak Tech', fullName: 'Slovak University of Technology', country: 'SK', city: 'Bratislava' },
  
  { name: 'Uni Malta', fullName: 'University of Malta', country: 'MT', city: 'Msida' },
  
  { name: 'Cyprus University', fullName: 'University of Cyprus', country: 'CY', city: 'Nicosia' },
  { name: 'Cyprus Tech', fullName: 'Cyprus University of Technology', country: 'CY', city: 'Limassol' },
  
  { name: 'Iceland University', fullName: 'University of Iceland', country: 'IS', city: 'Reykjavik' },
  { name: 'Reykjavik University', fullName: 'Reykjavik University', country: 'IS', city: 'Reykjavik' },
  
  { name: 'Tel Aviv', fullName: 'Tel Aviv University', country: 'IL', city: 'Tel Aviv' },
  { name: 'Hebrew University', fullName: 'Hebrew University of Jerusalem', country: 'IL', city: 'Jerusalem' },
  { name: 'Technion', fullName: 'Technion - Israel Institute of Technology', country: 'IL', city: 'Haifa' },
  { name: 'Weizmann', fullName: 'Weizmann Institute of Science', country: 'IL', city: 'Rehovot' },
  
  { name: 'AUB', fullName: 'American University of Beirut', country: 'LB', city: 'Beirut' },
  { name: 'AUC', fullName: 'American University in Cairo', country: 'EG', city: 'Cairo' },
  { name: 'Cairo University', fullName: 'Cairo University', country: 'EG', city: 'Cairo' },
  
  { name: 'King Saud', fullName: 'King Saud University', country: 'SA', city: 'Riyadh' },
  { name: 'KAUST', fullName: 'King Abdullah University of Science and Technology', country: 'SA', city: 'Thuwal' },
  { name: 'KFUPM', fullName: 'King Fahd University of Petroleum and Minerals', country: 'SA', city: 'Dhahran' },
  
  { name: 'AUD', fullName: 'American University of Dubai', country: 'AE', city: 'Dubai' },
  { name: 'AUS', fullName: 'American University of Sharjah', country: 'AE', city: 'Sharjah' },
  { name: 'Khalifa University', fullName: 'Khalifa University', country: 'AE', city: 'Abu Dhabi' },
  
  { name: 'Qatar University', fullName: 'Qatar University', country: 'QA', city: 'Doha' },
  { name: 'Texas A&M Qatar', fullName: 'Texas A&M University at Qatar', country: 'QA', city: 'Doha' },
  
  { name: 'UNAM', fullName: 'Universidad Nacional Autónoma de México', country: 'MX', city: 'Mexico City' },
  { name: 'Tec de Monterrey', fullName: 'Tecnológico de Monterrey', country: 'MX', city: 'Monterrey' },
  { name: 'IPN', fullName: 'Instituto Politécnico Nacional', country: 'MX', city: 'Mexico City' },
  
  { name: 'USP', fullName: 'University of São Paulo', country: 'BR', city: 'São Paulo' },
  { name: 'Unicamp', fullName: 'University of Campinas', country: 'BR', city: 'Campinas' },
  { name: 'UFRJ', fullName: 'Federal University of Rio de Janeiro', country: 'BR', city: 'Rio de Janeiro' },
  { name: 'PUC-Rio', fullName: 'Pontifical Catholic University of Rio de Janeiro', country: 'BR', city: 'Rio de Janeiro' },
  
  { name: 'UBA', fullName: 'University of Buenos Aires', country: 'AR', city: 'Buenos Aires' },
  { name: 'UC Chile', fullName: 'Pontifical Catholic University of Chile', country: 'CL', city: 'Santiago' },
  { name: 'U de Chile', fullName: 'University of Chile', country: 'CL', city: 'Santiago' },
  { name: 'UniAndes', fullName: 'University of the Andes', country: 'CO', city: 'Bogotá' },
  
  { name: 'Uni Auckland', fullName: 'University of Auckland', country: 'NZ', city: 'Auckland' },
  { name: 'Otago', fullName: 'University of Otago', country: 'NZ', city: 'Dunedin' },
  { name: 'Victoria Wellington', fullName: 'Victoria University of Wellington', country: 'NZ', city: 'Wellington' },
  
  { name: 'IIT Bombay', fullName: 'Indian Institute of Technology Bombay', country: 'IN', city: 'Mumbai' },
  { name: 'IIT Delhi', fullName: 'Indian Institute of Technology Delhi', country: 'IN', city: 'New Delhi' },
  { name: 'IIT Madras', fullName: 'Indian Institute of Technology Madras', country: 'IN', city: 'Chennai' },
  { name: 'IIT Kanpur', fullName: 'Indian Institute of Technology Kanpur', country: 'IN', city: 'Kanpur' },
  { name: 'IISc Bangalore', fullName: 'Indian Institute of Science', country: 'IN', city: 'Bangalore' },
  { name: 'Delhi University', fullName: 'University of Delhi', country: 'IN', city: 'Delhi' },
  
  { name: 'HKBU', fullName: 'Hong Kong Baptist University', country: 'HK', city: 'Hong Kong' },
  { name: 'CityU HK', fullName: 'City University of Hong Kong', country: 'HK', city: 'Hong Kong' },
  { name: 'PolyU', fullName: 'Hong Kong Polytechnic University', country: 'HK', city: 'Hong Kong' },
  
  { name: 'Nanjing University', fullName: 'Nanjing University', country: 'CN', city: 'Nanjing' },
  { name: 'Shanghai Jiao Tong', fullName: 'Shanghai Jiao Tong University', country: 'CN', city: 'Shanghai' },
  { name: 'USTC', fullName: 'University of Science and Technology of China', country: 'CN', city: 'Hefei' },
  { name: 'Wuhan University', fullName: 'Wuhan University', country: 'CN', city: 'Wuhan' },
  { name: 'Beihang', fullName: 'Beihang University', country: 'CN', city: 'Beijing' },
  
  { name: 'Keio', fullName: 'Keio University', country: 'JP', city: 'Tokyo' },
  { name: 'Waseda', fullName: 'Waseda University', country: 'JP', city: 'Tokyo' },
  { name: 'Nagoya University', fullName: 'Nagoya University', country: 'JP', city: 'Nagoya' },
  { name: 'Hokkaido University', fullName: 'Hokkaido University', country: 'JP', city: 'Sapporo' },
  { name: 'Kyushu University', fullName: 'Kyushu University', country: 'JP', city: 'Fukuoka' },
  
  { name: 'POSTECH', fullName: 'Pohang University of Science and Technology', country: 'KR', city: 'Pohang' },
  { name: 'SKKU', fullName: 'Sungkyunkwan University', country: 'KR', city: 'Seoul' },
  { name: 'Hanyang', fullName: 'Hanyang University', country: 'KR', city: 'Seoul' },
  
  { name: 'Chulalongkorn', fullName: 'Chulalongkorn University', country: 'TH', city: 'Bangkok' },
  { name: 'Mahidol', fullName: 'Mahidol University', country: 'TH', city: 'Bangkok' },
  
  { name: 'Uni Indonesia', fullName: 'University of Indonesia', country: 'ID', city: 'Jakarta' },
  { name: 'ITB', fullName: 'Bandung Institute of Technology', country: 'ID', city: 'Bandung' },
  { name: 'Gadjah Mada', fullName: 'Gadjah Mada University', country: 'ID', city: 'Yogyakarta' },
  
  { name: 'Uni Malaya', fullName: 'University of Malaya', country: 'MY', city: 'Kuala Lumpur' },
  { name: 'UTM', fullName: 'Universiti Teknologi Malaysia', country: 'MY', city: 'Johor Bahru' },
  { name: 'UKM', fullName: 'Universiti Kebangsaan Malaysia', country: 'MY', city: 'Bangi' },
  
  { name: 'UP Diliman', fullName: 'University of the Philippines Diliman', country: 'PH', city: 'Quezon City' },
  { name: 'Ateneo Manila', fullName: 'Ateneo de Manila University', country: 'PH', city: 'Manila' },
  
  { name: 'VNU Hanoi', fullName: 'Vietnam National University, Hanoi', country: 'VN', city: 'Hanoi' },
  { name: 'VNU HCMC', fullName: 'Vietnam National University, Ho Chi Minh City', country: 'VN', city: 'Ho Chi Minh City' },
  
  { name: 'Cape Town', fullName: 'University of Cape Town', country: 'ZA', city: 'Cape Town' },
  { name: 'Witwatersrand', fullName: 'University of the Witwatersrand', country: 'ZA', city: 'Johannesburg' },
  { name: 'Stellenbosch', fullName: 'Stellenbosch University', country: 'ZA', city: 'Stellenbosch' },
  { name: 'Pretoria', fullName: 'University of Pretoria', country: 'ZA', city: 'Pretoria' },
]

export function searchUniversities(query: string) {
  if (!query || query.length < 1) return []

  const queryLower = query.toLowerCase()
  
  return universities
    .map(uni => {
      const nameLower = uni.name.toLowerCase()
      const fullNameLower = uni.fullName.toLowerCase()
      
      const exactMatch = nameLower === queryLower
      const startsWithName = nameLower.startsWith(queryLower)
      const includesName = nameLower.includes(queryLower)
      const startsWithFullName = fullNameLower.startsWith(queryLower)
      const includesFullName = fullNameLower.includes(queryLower)
      
      let score = 0
      if (exactMatch) score = 100
      else if (startsWithName) score = 90
      else if (includesName) score = 80
      else if (startsWithFullName) score = 70
      else if (includesFullName) score = 60
      else return null
      
      return { ...uni, score }
    })
    .filter((uni): uni is NonNullable<typeof uni> => uni !== null)
    .sort((a, b) => {
      if (b.score !== a.score) return b.score - a.score
      return a.name.localeCompare(b.name)
    })
    .slice(0, 10)
}
